apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: vcpp-demo-tkg            # pick a cluster name
  namespace: vcpp-team   # choose a SV cluster namespace
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall # vmclass to be used for master(s)
      storageClass: wcp-policy  # your storage policy name here
    workers:
      count: 1
      class: best-effort-xsmall # vmclass to be used for workers(s)
      storageClass: wcp-policy  # your storage policy name here
  distribution:
    version: v1.16.8
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
